spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-service?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # You can change this to 'create' for initial setup

server:
  port: 8081 # Adjust as needed

# Other application-specific configurations
